version: "3.8"

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: aagc-dynamodb-local
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    working_dir: /home/dynamodblocal
    volumes:
      - ./data:/home/dynamodblocal/data
    restart: unless-stopped
